# Generated by Django 4.2.5 on 2023-11-05 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('man', models.BooleanField(default=False)),
                ('woman', models.BooleanField(default=False)),
                ('boy', models.BooleanField(default=False)),
                ('girl', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),  # noqa: E501
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('size', models.CharField(choices=[('2C', '2C'), ('3C', '3C'), ('4C', '4C'), ('5C', '5C'), ('6C', '6C'), ('7C', '7C'), ('8C', '8C'), ('9C', '9C'), ('10C', '10C'), ('10.5C', '10.5C'), ('11C', '11C'), ('11.5C', '11.5C'), ('12C', '12C'), ('12.5C', '12.5C'), ('13C', '13C'), ('13.5C', '13C.5'), ('1Y', '1Y'), ('1.5Y', '1.5Y'), ('2Y', '2Y'), ('2.5Y', '2.5Y'), ('3Y', '3Y'), ('3.5Y', '3.5Y'), ('4Y', '4Y'), ('4.5Y', '4.5Y'), ('5Y', '5Y'), ('5.5Y', '5.5Y'), ('6Y', '6Y'), ('6.5Y', '6.5Y'), ('7Y', '7Y'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11'), ('11.5', '11.5'), ('12', '12'), ('12.5', '12.5'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=5)),  # noqa: E501
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),  # noqa: E501
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('image', models.ImageField(upload_to='shoes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),  # noqa: E501
            ],
        ),
    ]
