# Generated by Django 4.2.5 on 2023-11-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_boy_remove_product_girl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='asdasdasd',
            field=models.BooleanField(default=False),
        ),
    ]
