# Generated by Django 4.2.5 on 2023-11-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image_asdasdasd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='asdasdasd',
        ),
    ]
