# Generated by Django 4.2.5 on 2023-11-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_image_asdasdasd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
