# Generated by Django 4.2.5 on 2023-10-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_size_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='id_product',
            new_name='product',
        ),
    ]
