# Generated by Django 4.2.5 on 2023-11-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=132, upload_to='shoes'),
            preserve_default=False,
        ),
    ]
