# Generated by Django 4.2.5 on 2023-11-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_item',
            field=models.BooleanField(default=False),
        ),
    ]
