# Generated by Django 4.2.5 on 2023-10-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_gender_alter_inventory_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='product',
        ),
        migrations.AddField(
            model_name='gender',
            name='product',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
