# Generated by Django 4.2.5 on 2023-11-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
