# Generated by Django 4.2.5 on 2023-11-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cart_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.inventory'),
            preserve_default=False,
        ),
    ]
